services:
  - type: web
    name: fingercloak-api
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: "npm ci"
    startCommand: "npm start"
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production

      # ВСЕ фронтовые origin'ы через запятую (без путей)
      - key: ALLOWED_ORIGINS
        value: "https://fingercloak.com,https://www.fingercloak.com,https://nikitasitlivy.github.io,http://localhost:5173,http://127.0.0.1:5173"

      - key: INDEXNOW_HOST
        value: "fingercloak.com"
      - key: INDEXNOW_KEY
        sync: false
      - key: INDEXNOW_KEY_LOCATION
        value: "https://fingercloak.com/indexnow.txt"

      # соль для анонимизации IP/ключей — выставь секретом
      - key: IP_HMAC_SALT
        sync: false

      # опционально: если на сервис добавлен persistent disk — будем писать JSONL
      # - key: WRITE_DIR
      #   value: "/data"
