services:
  - type: web
    name: fingercloak-api
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: "npm ci"
    startCommand: "npm start"
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production

      # Разрешённые фронтовые origin'ы (без путей), через запятую
      - key: ALLOWED_ORIGINS
        value: "https://fingercloak.com,https://www.fingercloak.com,https://nikitasitlivy.github.io"

      # Доверять X-Forwarded-For (Render проксирует IP)
      - key: TRUST_PROXY
        value: "true"

      # Соль для HMAC анонимизации IP — установить секретом
      - key: IP_HMAC_SALT
        sync: false

      # IndexNow (если используешь)
      - key: INDEXNOW_HOST
        value: "fingercloak.com"
      - key: INDEXNOW_KEY
        sync: false
      - key: INDEXNOW_KEY_LOCATION
        value: "https://fingercloak.com/indexnow.txt"

      # HMAC для ingest-запросов с Edge/TLS сенсора (если включены)
      - key: EDGE_SHARED_SECRET
        sync: false
      - key: TLS_SHARED_SECRET
        sync: false

      # Redis (опционально — если несколько инстансов/нужно переживать рестарты/увеличить TTL чанков)
      - key: REDIS_URL
        value: "redis://default:AfU3AAIncDFhMTVkZWY4NDIyMjU0Y2ZkOTM2YTQ1MTYyZGU3OTdiZXAxNjI3NzU@possible-phoenix-62775.upstash.io:6379"


      # Включить RDAP/WHOIS обогащение (через rdap.org)
      - key: RDAP_ENABLE
        value: "1"
      - key: RDAP_TIMEOUT_MS
        value: "4000"
      # === Chunks/Collect sync ===
      - key: CHUNKS_TTL_MS          # сколько храним сетевые чанки (edge/dns/webrtc/tls/tcp)
        value: "15000"              # 15s (можно 25000 на «медленных» сетях)

      - key: COLLECT_WAIT_FOR       # какие чанки дожидаться перед сохранением снимка
        value: "webrtc,dns,edge,tls,tcp"

      - key: COLLECT_TIMEOUT_MS     # сколько ждать в /api/fp/collect
        value: "8000"               # 8s (под дружелюбные сети — 6000; под тяжёлые — 12000)

      - key: DNS_SHARED_SECRET
        sync: false
      - key: WEBRTC_SHARED_SECRET
        sync: false
      - key: TCP_SHARED_SECRET
        sync: false